test: &default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: AdJgfnFWNffgVcad6mFk1V6HKax6149i3Ia9FVU3EeGW631_19wgdsLXazGf6dUH_GfsBqWyL1bYTmmT
  PAYPAL_CLIENT_SECRET: EFeMgZgC9SiP-8SP6dppT8fKc4CiejNKFeK2WBcNB_kpgutTh_kaeBSp_Qhwx-25uSvljg7-m7K2rJRg
  STRIPE_PUBLISHABLE_KEY: pk_test_51Hrp5MBhWCnlJeK62YxEYr8PeVemCHTFdgqYwSTkDhIjNqe5CQtnLOHUQvMCj0rxQXQzbhBGUlZGaYd5lHOOlEQy00QxNnNMLc
  STRIPE_SECRET_KEY: sk_test_51Hrp5MBhWCnlJeK6pJVCTbQNAh8gHxTIiY8LQH883kJ1YO8z084GC2Vi4254wzCyPVg86kE09DPJrWCyDrexNfU100HqRfVNVd
development:
  <<: *default
  PAYPAL_ENV: sandbox
  PAYPAL_CLIENT_ID: AdJgfnFWNffgVcad6mFk1V6HKax6149i3Ia9FVU3EeGW631_19wgdsLXazGf6dUH_GfsBqWyL1bYTmmT
  PAYPAL_CLIENT_SECRET: EFeMgZgC9SiP-8SP6dppT8fKc4CiejNKFeK2WBcNB_kpgutTh_kaeBSp_Qhwx-25uSvljg7-m7K2rJRg
  STRIPE_PUBLISHABLE_KEY: pk_test_51Hrp5MBhWCnlJeK62YxEYr8PeVemCHTFdgqYwSTkDhIjNqe5CQtnLOHUQvMCj0rxQXQzbhBGUlZGaYd5lHOOlEQy00QxNnNMLc
  STRIPE_SECRET_KEY: sk_test_51Hrp5MBhWCnlJeK6pJVCTbQNAh8gHxTIiY8LQH883kJ1YO8z084GC2Vi4254wzCyPVg86kE09DPJrWCyDrexNfU100HqRfVNVd